name: 💡 Shared
description: 소통해요
title: "🎫 [Tags] - <title>"

body:
  - type: dropdown
    id: type
    attributes:
      label: Curriculum
      options:
        - 📄 섹션 1. Object 클래스
        - 📄 섹션 2. 불변 객체
        - 📄 섹션 3. String 클래스
        - 📄 섹션 4. 래퍼, Class 클래스
        - 📄 섹션 5. 열거형 - ENUM
        - 📄 섹션 6. 날짜와 시간
        - 📄 섹션 7. 중첩 클래스, 내부 클래스1
        - 📄 섹션 8. 중첩 클래스, 내부 클래스2
        - 📄 섹션 9. 예외 처리1 - 이론
        - 📄 섹션 10. 예외 처리2 - 실습
        - 📄 섹션 11. 다음으로
  - type: textarea
    id: improvements-summary
    attributes:
      label: Details about changes
      description: 섹션에 대해 나눌 토픽을 작성 해주세요.
      placeholder: "자세한 설명을 적어주세요."
    validations:
      required: true
