name: 💡 Improvements
description: Create a new ticket for a new feature request
title: "🎫 [Tags] - <title>"

body:
  - type: dropdown
    id: type
    attributes:
      label: Which area of this project could be most improved?
      options:
        - 📄 Documentation
        - 👬 Pull request review
        - ❗Bug fix
        - 🔗 Features
        - 💡Idea
  - type: textarea
    id: improvements-summary
    attributes:
      label: Details about changes
      description: 추가 기능 또는 기능 수정에 대한 요구사항을 작성 해주세요.
      placeholder: "자세한 설명을 적어주세요."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Required
      options:
        - label: Assigee 설정
        - label: Issue label 설정
        - label: 개선사항 내용 작성
